name: OWASP ZAP Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: "https://anima-news.netlify.app"
          cmd_options: "-a"

      - name: List files (debug)
        run: ls -R

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report   # <--- disini ganti namanya
          path: report_html.html
